### ISSUE TITLE
Mailer test occasionally fails. 

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#423]
# Bug Report
## What is the current behavior?
```powershell
Run options: --seed 58806

# Running:

.......................................................S.........................................................................F

Failure:
UserMailerTest#test_renders_the_body [/app/test/mailers/user_mailer_test.rb:22]:
--- expected
+++ actual
@@ -1,4 +1,4 @@
-"Clovis O&#39;Reilly, has joined. They're located within 50 miles of your chapter!
+"Clovis O'Reilly, has joined. They're located within 50 miles of your chapter!
 Please email them at ena@hickle.name and welcome them, and consider providing info on the next local meetup.
 Let's encourage in-person involvement within Operation Code!
 "

/bundle/gems/railties-5.0.7/lib/rails/test_unit/reporter.rb:70:in `method': undefined method `test_renders_the_body' for class `Minitest::Result' (NameError)
        from /bundle/gems/railties-5.0.7/lib/rails/test_unit/reporter.rb:70:in `format_rerun_snippet'
        from /bundle/gems/railties-5.0.7/lib/rails/test_unit/reporter.rb:23:in `record'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:803:in `block in record'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:802:in `each'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:802:in `record'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
        from /bundle/gems/railties-5.0.7/lib/rails/test_unit/line_filtering.rb:9:in `run'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
        from /bundle/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
```

## What is the expected behavior?
When I run tests failure is not randomized.

**Comment by BRIMIL01** [comment]
Looks like the username is not getting escaped in the expected value.
